version: '3'
services:
    nginx:
        build: ./Docker-nginx
        links:
            - node1:node1
            - node2:node2
            - node3:node3
        ports:
            - "5001:80"
        networks:
        - frontend
        - backend
    node1:
        build: ./Docker-node
        links:
            - redis
        ports:
            - "8080"
        volumes:
            - ./Docker-node/:/home/app
            - /home/app/node_modules
        networks:
        - backend
    node2:
        build: ./Docker-node
        links:
            - redis
        ports:
            - "8080"
        volumes:
            - ./Docker-node/:/home/app
            - /home/app/node_modules
        networks:
        - backend        
    node3:
        build: ./Docker-node
        links:
            - redis
        ports:
            - "8080"
        volumes:
            - ./Docker-node/:/home/app
            - /home/app/node_modules
        networks:
        - backend        
    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
        - backend       
networks:
   frontend:
   backend: